version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - "./backend/db.sqlite3:/app/db.sqlite3"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:80"
    volumes:
      - ./react:/app
      - frontend_dist:/app/dist  # Itt használjuk a közös volumet
    stdin_open: true
    tty: true

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - frontend_dist:/usr/share/nginx/html  # Itt csatoljuk a közös volumet
      - ../../../../../../../../etc/nginx/sites-available/vizsgaremek:/etc/nginx/conf.d/default.conf
      - ../../../../../../../../etc/letsencrypt/live/uni-support.sytes.net/fullchain.pem:/etc/letsencrypt/live/uni-support.sytes.net/fullchain.pem
      - ../../../../../../../../etc/letsencrypt/live/uni-support.sytes.net/privkey.pem:/etc/letsencrypt/live/uni-support.sytes.net/privkey.pem

volumes:
  frontend_dist:  # Itt definiáljuk a közös volumet