version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - "/c/Users/Csongor Kiss/Desktop/Web Development/Modern-React-UI-UX/backend/db.sqlite3:/app/db.sqlite3"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:80"
    volumes:
      - ./react:/app
    stdin_open: true
    tty: true
