version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - "./backend/db.sqlite3:/app/db.sqlite3"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=uni-support.sytes.net, localhost

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - react-build:/app/dist
    stdin_open: true
    tty: true

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - react-build:/usr/share/nginx/html
      - ../../../../../../../../etc/nginx/sites-available/vizsgaremek:/etc/nginx/conf.d/default.conf
      - ../../../../../../../../etc/letsencrypt/live/uni-support.sytes.net/fullchain.pem:/etc/letsencrypt/live/uni-support.sytes.net/fullchain.pem
      - ../../../../../../../../etc/letsencrypt/live/uni-support.sytes.net/privkey.pem:/etc/letsencrypt/live/uni-support.sytes.net/privkey.pem

volumes:
  react-build: